### PR TITLE
fix: Hybrid CommonJS/ESM module support

### PR DESCRIPTION
**Pull request by shaungrady**
The packages in this repo aren't correctly configured as either CommonJS or ESM modules. This PR makes use of the [`tshy`](https://github.com/isaacs/tshy) package to handle generated a hybrid build that supports both module systems.

### CODE REVIEW

**Comment by shaungrady** [comment]
@STDSuperman Let me know if you need any more information about this. I'm unable to use this lib in a NextJS app because it's using ES module imports without being correctly configured as an ES module. `tshy` is a great lib written by the same person who wrote `npm`.

**Comment by STDSuperman** [comment]
> @STDSuperman Let me know if you need any more information about this. I'm unable to use this lib in a NextJS app because it's using ES module imports without being correctly configured as an ES module. `tshy` is a great lib written by the same person who wrote `npm`.

Thank you very much for your contribution! However, for the sake of ecosystem compatibility and stability, I prefer to use Rollup. I will provide support for this in the next couple of days.

**Comment by shaungrady** [comment]
I'm not looking for a bundle, just a fully ES module-compatible build.

**Comment by STDSuperman** [comment]
> I'm not looking for a bundle, just a fully ES module-compatible build.

Got it, I'm working on it and should have it done today.

**Comment by STDSuperman** [comment]
The issue you mentioned has been resolved, and the latest version is `1.0.23`.

**Comment by shaungrady** [comment]
Thank you!

**Pull request closed without merging**
